D-TACQ/acq400_hapi

- acq400_hapi/acq400.py
- acq400_hapi/awg_data.py
- acq400_hapi/netclient.py
- user_apps/acq1001/acq1001_awg_demo.py
- user_apps/acq1001/run_gpg.py
- user_apps/acq1001/run_livetop.py
- user_apps/acq1014/acq1014_caploop.py
- user_apps/acq1014/acq1014_configure_transient.py
- user_apps/acq2106/acq2106_set_sync_role.py
- user_apps/acq400/acq400_abort.py
- user_apps/acq400/acq400_caploop_rtrig.py
- user_apps/acq400/acq400_capture.py
- user_apps/acq400/acq400_checkramp.py
- user_apps/acq400/acq400_configure_transient.py
- user_apps/acq400/acq400_reboot.py
- user_apps/acq400/acq400_remote_script.py
- user_apps/acq400/acq400_stream.py
- user_apps/acq400/acq400_upload.py
- user_apps/acq400/delay_trigger_setup.py
- user_apps/acq400/make_clktrg_chain.py
- user_apps/acq400/set_burst.py
- user_apps/hil/hil.py
- user_apps/hil/hil_plot.py
- user_apps/special/acq480_controls.py
- user_apps/utils/bin2csv.py
Contains changes to acq400_stream.py (use byte strings), removes configure transient redundant lines, changes netclient to use latin1 for python 3 compatibility and tab fixes.
> Python 3 changes

- user_apps/acq400/acq400_stream.py
Use 1M, 1k etc as filesize and totaldata arguments.
> Changes in order to use intSI in command line args.

- acq400_hapi/acq400.py
> Updated SIG_SRC_TRG_0 to HDMI over HDMI_TRG

- user_apps/analysis/host_demux.py
Changed global variables and made them into arguments. 
Also changed how the uut name was found and displayed in KST. Previously it was taken from args.the_uut. This was the case even when egu was not being used by the user. Changed to the uut provided by the user.
> Removed global variables and made them into arguments. 

- user_apps/acq2106/run-hts-all.py
- user_apps/acq400/sync_role.py
- user_apps/analysis/host_demux.py
> Fixed drive letter and pykst import bugs.

- user_apps/special/awg_oneshot_speed_test.py
modified:   user_apps/special/awg_oneshot_speed_test.py
Tabs were mixed with spaces on the same line.
> Fixed indentation issues.

- test_apps/phase_delay.py
new file:   phase_delay.py
phase_delay.py is a script that analyses the
differences between two digitized waves.
> Added working version of phase delay evaluator.

- test_apps/sync_trg_test.py
modified:   test_apps/sync_trg_test.py
> Added a postshot validator.

- user_apps/special/bolo8_cal_cap_loop.py
modified:   bolo8_cal_cap_loop.py
Added support for rising and falling
external triggers on capture only.
Calibration requires soft_trigger.
> Fixed bolo8 triggers. Added proper external trigger support.

- test_apps/phase_delay.py
modified:   test_apps/phase_delay.py
> Fixed maths errors in phase delay calc.

- test_apps/MA/make_mag_buffs.py
> Set values explicitly as ints to work in python3

- acq400_hapi/acq400.py
modified:   acq400.py
Need to call the load_stl function with a
"self." since the function we are calling
is also inside the class.
> Added self.load_stl to function call.

- user_apps/acq400/acq400_stream2.py
modified:   acq400_stream2.py
Previously this script was using raw_input and
sys.maxint, neither of which are available on
python 3. Changed these for python 2 and 3
compatible replacements.
> Added support for python 3 in acq400_stream2.py.

- user_apps/acq400/sync_role.py
> Changed the print statement in sync_role.py for python3.

- test_apps/MA/make_mag_buffs.py
> Added a way to add 0 padding to the MA dat file.

- user_apps/acq400/acq400_streamtonowhere.py
Added a script that does a streamtonowhered so we don't saturate the ethernet link when streaming during LLC.
> Added a new streamtonowhere script.

- test_apps/t_latch_histogram.py
- user_apps/acq400/acq400_configure_transient.py
Previously the T_LATCH was analysed by iteration. Now it is analysed faster using numpy and many threads. Time to analyse is vastly reduced.
> T latch speed increase.

- user_apps/acq2106/mgtdramshot.py
Previously the data was checked by subtracting the first array elements value from the rest. This method checked the data inside the buffer was good, but did not check that the data in consecutive buffers was correct. Now the cycle number is used to ADD the (cycle * last element of the first buffer) to the first buffer so we can check that the buffers are consecutive.
i.e. Nth buffer = (1st buf) + (N * (last elem of 1st buf))
> Made some improvements to the way in which the simulated data is verified.

- user_apps/acq2106/mgtdramshot.py
modified:   user_apps/acq2106/mgtdramshot.py
> Added samples to make the printout message clearer.

- test_apps/check_transition.py
new file:   check_transition.py
> Added a script to check trigger locations.

- user_apps/acq400/acq400_streamtonowhere.py
modified:   acq400_streamtonowhere.py
> Improved streamtonowhere so the script will wait on each UUT to arm.

- user_apps/acq400/acq400_rtm_stream.py
new file:   user_apps/acq400/acq400_rtm_stream.py
> Added a script to stream rtm data from port 4210.

- user_apps/analysis/host_demux.py
modified:   host_demux.py
Note that pykst is not available on python3, so only
matplotlib will work on python3.
> Made host_demux function on python3.

- test_apps/pyepics_control.py
new file:   test_apps/pyepics_control.py
> Added a new pyepics control example.

- user_apps/acq1001/acq1001_awg_demo.py
- user_apps/acq1001/run_gpg.py
- user_apps/acq2106/acq2106_set_sync_role.py
- user_apps/acq2106/mgtdramshot.py
- user_apps/acq2106/ustc_set_sync.role.py
- user_apps/acq400/acq400_awg_load1.py
- user_apps/analysis/cpsc2_test.py
- user_apps/analysis/go_demux.py
- user_apps/hil/hil.py
- user_apps/hil/hil_plot.py
- user_apps/hil/hil_plot_hi_gain.py
modified:   user_apps/acq1001/acq1001_awg_demo.py
modified:   user_apps/acq1001/run_gpg.py
modified:   user_apps/acq2106/acq2106_set_sync_role.py
modified:   user_apps/acq2106/mgtdramshot.py
modified:   user_apps/acq2106/ustc_set_sync.role.py
modified:   user_apps/acq400/acq400_awg_load1.py
modified:   user_apps/analysis/cpsc2_test.py
modified:   user_apps/analysis/go_demux.py
modified:   user_apps/hil/hil.py
modified:   user_apps/hil/hil_plot.py
modified:   user_apps/hil/hil_plot_hi_gain.py
> Made all calls to future only if python version < 3.

- acq400_hapi/acq400_ui.py
- acq400_hapi/acq400_uut_handler.py
- test_apps/json_uut_load.py
modified:   ../acq400_hapi/acq400_ui.py
new file:   ../acq400_hapi/acq400_uut_handler.py
new file:   json_uut_load.py
> Added new uut handler to load UUTs from JSON.

- user_apps/acq400/CAPTURE_README.md
The README covers the few basic commands needed to fully configure a system and then take a transient capture.
> Added a new README to the user_apps/acq400 directory.

- user_apps/acq400/AWG_README.md
This README covers most of the items required to get set up with making an AWG waveform and testing the outputs using an AI card.
> Added an AWG_README.md.

- user_apps/acq400/AWG_README.md
modified:   user_apps/acq400/AWG_README.md
> Fixed a typo.

- user_apps/acq400/acq400_configure_transient.py
- user_apps/acq400/acq400_load_awg.py
modified:   user_apps/acq400/acq400_configure_transient.py
> Fixed a bug when running configure_transient from cmd line.

- user_apps/acq400/acq400_upload.py
modified:   user_apps/acq400/acq400_upload.py
> Upload only wouldn't work in upload.py. Now fixed.

- user_apps/acq400/acq400_stream2.py
modified:   user_apps/acq400/acq400_stream2.py
> Changes for es_stream for stream2.py.

- acq400_hapi/acq400.py
- acq400_hapi/shotcontrol.py
- user_apps/acq400/acq400_es_split.py
- user_apps/acq400/acq400_stream2.py
- user_apps/acq400/acq400_upload.py
- user_apps/acq400/set_burst.py
Necessary changes for RTM stream.
> RTM Stream

- acq400_hapi/acq400_ui.py
modified:   acq400_hapi/acq400_ui.py
> Fixed broken trigger behaviour.

- user_apps/acq400/acq400_upload.py
modified:   user_apps/acq400/acq400_upload.py
> Added UI to upload.py.

- test_apps/radcelf_sync_test.py
modified:   test_apps/radcelf_sync_test.py
Bug would complain with different transition
array lengths.
> Fixed a bug with radcelf_sync_test.py.

- scripts/run-stream-ramdisk-ramp
- user_apps/acq2106/hts_multistream.py
new file:   scripts/run-stream-ramdisk-ramp
Added check ramp option to hts_multistream
> samuel@humla

- scripts/run-stream-ramdisk-count
- scripts/run-stream-ramdisk-ramp
- user_apps/acq2106/hts_multistream.py
sam@humla	
new file:   scripts/run-stream-ramdisk-count
modified:   scripts/run-stream-ramdisk-ramp
> Added spad checking option

- acq400_hapi/acq400.py
- scripts/run-stream-ramdisk-count
- user_apps/acq2106/hts_multistream.py
modified:   scripts/run-stream-ramdisk-count
sam@humla
> Added z7io support

- acq400_hapi/afhba404.py
- user_apps/acq2106/hts_multistream.py
modified:   acq400_hapi/afhba404.py
sam@humla
> Moved Afhba functions into common module

- user_apps/acq2106/hts_multistream.py
> Fixed threads not stopping

- user_apps/acq2106/hts_multistream.py
> made spad use uut spad if no spad arg and general cleanup

- user_apps/acq2106/afhba_mon.py
new file:   user_apps/acq2106/afhba_mon.py
sam@humla
> Created afhba web monitor

- user_apps/acq2106/afhba_mon.py
modified:   user_apps/acq2106/afhba_mon.py
sam@humla
> Added simple and detailed toggle

- user_apps/acq2106/afhba_mon.py
modified:   user_apps/acq2106/afhba_mon.py
sam@humla
> Made buttons more descriptive and added links to uuts

- acq400_hapi/acq400.py
> Fixed acq2206 using basic hapi

- test_apps/phase_delay_multi.py
modified:   test_apps/phase_delay_multi.py
sam@humla
> Updated phase delay multi

- test_apps/bolo8_tester.py
new file:   test_apps/bolo8_tester.py
sam@humla
> Added automatic Bolo8 tester and logger

- test_apps/bolo8_tester.py
modified:   test_apps/bolo8_tester.py
sam@humla
> Added data format comment

- user_apps/acq2106/hts_multistream.py
> Fixed Trigger not working and trigger triggering multiple times

- user_apps/analysis/host_demux.py
modified:   user_apps/analysis/host_demux.py
sam@humla
> Added traces_per_plot argument

- acq400_hapi/acq400.py
- test_apps/test_dwg192.py
> Fixed read_channels not closing sockets

- test_apps/bolo8_tester.py
modified:   test_apps/bolo8_tester.py
sam@humla
> Now saves as csv

- test_apps/slowmon_validator.py
new file:   test_apps/slowmon_validator.py
sam@humla
> Added slowmon validator

- acq400_hapi/agilent33210.py
modified:   acq400_hapi/agilent33210.py
sam@humla
> Added beep method

- acq400_hapi/acq400.py
modified:   acq400.py
sam@humla
> Fixed older fimwares without has_knobs failing

- test_apps/DI460_tester.py
new file:   test_apps/DI460_tester.py
> Added DI460_tester.py

- test_apps/pv_monitor.py
new file:   test_apps/pv_monitor.py
> Added pv_monitor.py

- test_apps/DI460_tester.py
modified:   test_apps/DI460_tester.py
> Fixed signal values

- user_apps/acq400/sync_cluster.py
new file:   user_apps/acq400/sync_cluster.py
> added sync_cluster.py

- test_apps/DI460_tester.py
modified:   test_apps/DI460_tester.py
> Added verbose arg and better error reporting

- setpath2
new file:   setpath2
Uses file location as PYTHONPATH instead of current directory
> Added setpath2

- user_apps/analysis/cluster_plotter.py
new file:   user_apps/analysis/cluster_plotter.py
> Added cluster_plotter.py

- user_apps/analysis/cluster_plotter.py
modified:   user_apps/analysis/cluster_plotter.py
> Now plots single files

- user_apps/analysis/host_demux.py
modified:   user_apps/analysis/host_demux.py
> --save now accepts relative paths

- user_apps/analysis/cluster_plotter.py
modified:   user_apps/analysis/cluster_plotter.py
> Now plots chan > 1 correctly

- user_apps/acq400/acq400_stream_multi.py
modified:   user_apps/acq400/acq400_stream_multi.py
> Threads will stop when program exits

- user_apps/analysis/cluster_plotter.py
modified:   user_apps/analysis/cluster_plotter.py
> Handles starting cycle correctly now

- user_apps/acq400/acq400_stream_multi.py
modified:   user_apps/acq400/acq400_stream_multi.py
> Writes log file correctly and added display arg

- user_apps/acq400/acq400_stream_multi.py
modified:   user_apps/acq400/acq400_stream_multi.py
> Added combine arg

- user_apps/analysis/cluster_plotter.py
modified:   user_apps/analysis/cluster_plotter.py
> Added multiplot arg

- user_apps/analysis/host_demux.py
modified: user_apps/analysis/host_demux.py
> Fixed double_up arg

- MAKEDOC.README.md
> Added instructions to build documentation

- user_apps/web/compose_remote.py
modified:   user_apps/web/compose_remote.py
> Added segment arg

- user_apps/web/compose_remote.py
modified:   user_apps/web/compose_remote.py
> Detects api port automatically

- user_apps/web/compose_remote.py
modified:   user_apps/web/compose_remote.py
> Added queue arg to queue active segments

- user_apps/acq400/acq400_wait_state.py
new file:   user_apps/acq400/acq400_wait_state.py
> Added acq400_wait_state.py

- scripts/awg_interweave_loop.sh
new file:   scripts/awg_interweave_loop.sh
> Added awg_interweave_loop.sh

- acq400_hapi/shotcontrol.py
modified:   acq400_hapi/shotcontrol.py
> Added better labelling to plot

- user_apps/special/acq480_4CH_reuniter.py
new file:   user_apps/special/acq480_4CH_reuniter.py
> added acq480_4CH_reuniter.py

- user_apps/special/acq480_4CH_reuniter.py
modified:   user_apps/special/acq480_4CH_reuniter.py
This commit somehow failed to push
> Added remove_es arg

- acq400_hapi/acq400_ui.py
modified:   acq400_hapi/acq400_ui.py
> Added merge parsers method

- acq400_hapi/__init__.py
- acq400_hapi/acq400_logger.py
new file:   acq400_hapi/acq400_logger.py
modified:   acq400_hapi/__init__.py
> Added acq400_logger.py

- acq400_hapi/acq400.py
> Added missing cc.close() to read_decims

- acq400_hapi/acq400.py
> Added alternate read channels method with fixed inconsistencies regarding demux

- test_apps/bolo8_tester.py
modified:   test_apps/bolo8_tester.py
> Added -y arg to skip prompt

- test_apps/mgt508_push_pull_test.py
Runs a capture and fills MGT508 RAM, offloads and calculates sha1 hashes of the data.
Can use a simulated ramp function on all channels or can be set to acquire real data.
new file:   test_apps/mgt508_push_pull_test.py
> Add mgt508 push pull test

- user_apps/utils/wavegen.py
new file:   user_apps/utils/wavegen.py
> Added wavegen.py

- user_apps/utils/wavegen.py
modified:   user_apps/utils/wavegen.py
> fixed scaling in wavegen.py

- user_apps/utils/wavegen.py
modified:   user_apps/utils/wavegen.py
> Added voltage offset arg

- test_apps/anatrg_demo.py
new file:   test_apps/anatrg_demo.py
> Added anatrg_demo.py file

- acq400_hapi/acq400.py
- scripts/mgt508_read_mem
- user_apps/acq2206/mgt508_capture.py
Added argument for decimation to HAPI script, with neccessary plumbing for a decimation read to hit the correct port on the MGT508.
Also added flags to MGT capture script to read or pull individually.
> Add decimation option for read from MGT508 to host

- user_apps/pyepics/allison_demo.py
modified:   user_apps/pyepics/allison_demo.py
> Plots chan 5 separately

- user_apps/pyepics/allison_demo.py
modified:   user_apps/pyepics/allison_demo.py
> Corrected missing first transition error

- user_apps/pyepics/allison_demo.py
modified:   user_apps/pyepics/allison_demo.py
`
[acq2106_176, 0] > NCHAN
[acq2106_176, 0] < 20
[acq2106_176, 0] > STREAM_SUBSET_MASK = 0xf003f
[acq2106_176, 0] < 1
`
> Added trace arg

- acq400_hapi/acq400.py
Set value
uut.s0.stream_subset_mask = uut.get_subset_mask([1,2,3,4])
Get value
mask = uut.get_subset_mask()
print(mask) # [1,2,3,4]
> Added method to handle stream subset mask

- user_apps/analysis/octobee_viz.py
> Add example script for visualizing octobee sensor data in 3D
